apiVersion: v1
kind: Namespace
metadata:
  annotations:
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  name: githubactions-sample-dev
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: frontend
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  labels:
    app: guestbook
  name: guestbook
  namespace: githubactions-sample-dev
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: redis-master
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: githubactions-sample-dev
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: redis-slave
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: githubactions-sample-dev
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: frontend
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  name: frontend
  namespace: githubactions-sample-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      annotations:
        app: frontend
        build-id: 156881545
        git-branch: feat/switch
        git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
        git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
      labels:
        app: guestbook
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: k8s.gcr.io/guestbook:v3
        name: php-redis
        ports:
        - containerPort: 3000
          name: http-server
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: redis-master
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: githubactions-sample-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      annotations:
        app: redis-master
        build-id: 156881545
        git-branch: feat/switch
        git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
        git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
      labels:
        app: redis
        role: master
    spec:
      containers:
      - image: redis:latest
        name: redis-master
        ports:
        - containerPort: 6379
          name: redis-server
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: redis-slave
    build-id: 156881545
    git-branch: feat/switch
    git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
    git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: githubactions-sample-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      annotations:
        app: redis-slave
        build-id: 156881545
        git-branch: feat/switch
        git-link: https://github.com/guitarrapc/githubactions-lab/pull/15
        git-sha: 164aec2da1c1430c2cd0199e370c1ccf99f8634e
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - command:
        - redis-server
        - --slaveof
        - redis-master
        - "6379"
        image: redis:latest
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
